name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: opsless/ms-teams-github-action  
      - uses: opsless/ms-teams-github-actions@main
        with:
          MY_NAME: "I say hey, Mona"
